/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CTA: typeof import('./src/components/CTA.vue')['default']
    Features: typeof import('./src/components/Features.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Logo: typeof import('./src/components/logo.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Plans: typeof import('./src/components/Plans.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidenav: typeof import('./src/components/Sidenav.vue')['default']
    UAlert: typeof import('./../../node_modules/.bun/@nuxt+ui@4.1.0+668bdfb90e5f6941/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./../../node_modules/.bun/@nuxt+ui@4.1.0+668bdfb90e5f6941/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAuthForm: typeof import('./../../node_modules/.bun/@nuxt+ui@4.1.0+668bdfb90e5f6941/node_modules/@nuxt/ui/dist/runtime/components/AuthForm.vue')['default']
    UButton: typeof import('./../../node_modules/.bun/@nuxt+ui@4.1.0+668bdfb90e5f6941/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UColorModeSwitch: typeof import('./../../node_modules/.bun/@nuxt+ui@4.1.0+668bdfb90e5f6941/node_modules/@nuxt/ui/dist/runtime/vue/components/color-mode/ColorModeSwitch.vue')['default']
    UContainer: typeof import('./../../node_modules/.bun/@nuxt+ui@4.1.0+668bdfb90e5f6941/node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    UDashboardGroup: typeof import('./../../node_modules/.bun/@nuxt+ui@4.1.0+668bdfb90e5f6941/node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue')['default']
    UDashboardNavbar: typeof import('./../../node_modules/.bun/@nuxt+ui@4.1.0+668bdfb90e5f6941/node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue')['default']
    UDashboardPanel: typeof import('./../../node_modules/.bun/@nuxt+ui@4.1.0+668bdfb90e5f6941/node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue')['default']
    UDashboardSidebar: typeof import('./../../node_modules/.bun/@nuxt+ui@4.1.0+668bdfb90e5f6941/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue')['default']
    UError: typeof import('./../../node_modules/.bun/@nuxt+ui@4.1.0+668bdfb90e5f6941/node_modules/@nuxt/ui/dist/runtime/components/Error.vue')['default']
    UFooter: typeof import('./../../node_modules/.bun/@nuxt+ui@4.1.0+668bdfb90e5f6941/node_modules/@nuxt/ui/dist/runtime/components/Footer.vue')['default']
    UHeader: typeof import('./../../node_modules/.bun/@nuxt+ui@4.1.0+668bdfb90e5f6941/node_modules/@nuxt/ui/dist/runtime/components/Header.vue')['default']
    UIcon: typeof import('./../../node_modules/.bun/@nuxt+ui@4.1.0+668bdfb90e5f6941/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UKbd: typeof import('./../../node_modules/.bun/@nuxt+ui@4.1.0+668bdfb90e5f6941/node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue')['default']
    ULink: typeof import('./../../node_modules/.bun/@nuxt+ui@4.1.0+668bdfb90e5f6941/node_modules/@nuxt/ui/dist/runtime/vue/components/Link.vue')['default']
    UMain: typeof import('./../../node_modules/.bun/@nuxt+ui@4.1.0+668bdfb90e5f6941/node_modules/@nuxt/ui/dist/runtime/components/Main.vue')['default']
    UNavigationMenu: typeof import('./../../node_modules/.bun/@nuxt+ui@4.1.0+668bdfb90e5f6941/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPageCard: typeof import('./../../node_modules/.bun/@nuxt+ui@4.1.0+668bdfb90e5f6941/node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue')['default']
    UPageFeature: typeof import('./../../node_modules/.bun/@nuxt+ui@4.1.0+668bdfb90e5f6941/node_modules/@nuxt/ui/dist/runtime/components/PageFeature.vue')['default']
    UPageGrid: typeof import('./../../node_modules/.bun/@nuxt+ui@4.1.0+668bdfb90e5f6941/node_modules/@nuxt/ui/dist/runtime/components/PageGrid.vue')['default']
    UPageHero: typeof import('./../../node_modules/.bun/@nuxt+ui@4.1.0+668bdfb90e5f6941/node_modules/@nuxt/ui/dist/runtime/components/PageHero.vue')['default']
    UPageSection: typeof import('./../../node_modules/.bun/@nuxt+ui@4.1.0+668bdfb90e5f6941/node_modules/@nuxt/ui/dist/runtime/components/PageSection.vue')['default']
    UPricingPlans: typeof import('./../../node_modules/.bun/@nuxt+ui@4.1.0+668bdfb90e5f6941/node_modules/@nuxt/ui/dist/runtime/components/PricingPlans.vue')['default']
  }
}
